docs/team/panavdua.md
=> Create ppp for me

docs/team/junhao247.md
=> Add my own project portfolio page

docs/team/YanLing.md
=> Updated Yan Ling's PPP

.github/workflows/codecov.yml, README.md
Update according to #12 issues. Please take a look and suggest improvements.
=> Update JavaCI status badge and README documentation

docs/team/abenx162.md
=> Add Ben Xuan's PPP to docs/team

docs/UserGuide.md
Update delete feature for user guide
=> Update delete feature for user guide

docs/team/junhao247.md
Update Skeletal PPP to make it more uniform and proper, fixes #6
=> Update Skeletal PPP 

docs/team/yanling.md
=> Branch ppp

docs/team/yanling.md
=> Update Yan Ling's PPP

docs/UserGuide.md
=> Add table of contents to UserGuide.md

docs/_config.yml
Update site headings according to #43
=> Update config.yml in order to update site settings

docs/UserGuide.md
Accidentally deletes the automatic TOC, reverted it to the default one. #17
=> Change TOC in UserGuide.md

docs/DeveloperGuide.md
=> Add NFR to DeveloperGuide.md

docs/UserGuide.md
=> Add 'find' command details in UserGuide

docs/UserGuide.md
=> Update "edit" command in command summary of UserGuide.md

docs/AboutUs.md, docs/UserGuide.md
Update UserGuide to current UserGuide with appropriate format for "add" command according to #17
=> Update UserGuide for "add" command

docs/DeveloperGuide.md
fix #18 , update use cases 4, 5, 6
=> Update developer guide: Use cases 4,5,6

docs/AboutUs.md, docs/DeveloperGuide.md, docs/UserGuide.md
Update developer guide with Use cases 1 - 3 according to #18 
Minor edit to user guide and about us.
=> Update developer guide: Use cases 1, 2, 3

docs/DeveloperGuide.md
=> Update glossary of Developer guide

src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/resources/view/MainWindow.fxml
fixes #5, update deleteCommand
=> Branch delete command

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/model/person/EmployeeId.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/HelpWindow.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/PersonListCard.fxml
1) Create employeeId class
2) Update Command classes to take in employeeId in constructor
3) Update JsonAdaptedPerson so that employeeId is stored properly
4) Update SampleDataUtil with employeeId
Fixes #56
=> Create employeeId class, update Command, Ui, Parser and Person class

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/FindCommand.java
=> Branch find command

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddCommand.java
Update AddCommand and UserGuide to take in employeeId, fixes #7
=> Update AddCommand and UserGuide to take in employeeId

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/ListCommand.java
Update the list command to match ExecutivePro according to #73
=> Branch list command

src/main/java/seedu/address/logic/commands/AddCommand.java
=> Update example for AddCommand

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/model/person/EmployeeId.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/PersonCard.java
JsonAdaptedPerson and EmployeeId
so that database stores the inputs, fixes #56
=> Update Classes to fix the storage of inputs

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json, src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/model/person/EmployeeIdTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/TypicalPersons.java
Update PersonAddressBook class to include employeeId. Update LogicManagerTest to setEmployeeId.
Add employeeId in AddCommandParserTest, AddressBookParserTest. Create EmployeeIdTest class.
Update PersonBuilder,TypicalPersons class to include employeeId.
=> Update Test classes in order to resolve Java CI errors.

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java
Add feature to change department for employees, according to #61.
=> Add department to "edit" command

docs/UserGuide.md
Update user guide to include instructions for tags
=> Update user guide to include tags

src/main/java/seedu/address/logic/commands/CommandResult.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/ThemeCommandParser.java, src/test/java/seedu/address/logic/commands/CommandResultTest.java, src/test/java/seedu/address/logic/commands/ThemeCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/logic/parser/ThemeCommandParserTest.java, src/test/java/seedu/address/testutil/EmployeeUtil.java
Add test cases relating to theme commands according to #60 .
Todo in future PR: add test to ThemeCommandTest.java to check if the MainWindow's CSS file is changed.
=> Add test cases relating to Theme commands

docs/DeveloperGuide.md, docs/diagrams/plantuml/Style.puml
=> Update DG to include new delete sequence diagram

build.gradle, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/ExecutiveProDb.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java
Add getFullEmployeeList() and getEmployee() method in Model class. Change Edit/Delete command to use the full list instead of the filtered list, fixes #111 
Add Assertions to gradle file
=> Add methods in Model class

src/main/java/seedu/address/model/employee/EmployeeId.java, src/main/java/seedu/address/storage/JsonExecutiveProStorage.java, src/main/java/seedu/address/storage/JsonSerializableExecutiveProDb.java
Update EmployeeId class to fix the bug in max ID, fixes #96
=> Update EmployeeId class to fix bug in max ID

src/main/java/seedu/address/logic/commands/ClearCommand.java
Update ClearCommand to reset employeeId count so that the EmployeeId can be tracked from the start("1"), fixes #123
=> Update ClearCommand 

src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/PersonListCard.fxml
Remove fields that are not essential from EmployeeCard display, fixes #125
=> Remove fields from EmployeeCard

src/main/resources/view/PersonListPanel.fxml
Remove default picture, fixes #126
=> Fix UI Picture Bug

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/ui/CommandFormat.java, src/main/java/seedu/address/ui/HelpWindow.java, src/main/java/seedu/address/ui/UiManager.java, src/main/resources/view/HelpWindow.css, src/main/resources/view/HelpWindow.fxml
Change HelpWindow to become a pop-up table to view help for all functions, and for a more comprehensive guide, the user can visit the user guide in the website via the button "UserGuide", fixes #134
=> Change HelpWindow for better readability

docs/UserGuide.md
Update Userguide to include Theme and SetPicture commands according to #135.
=> Update Userguide to include Theme and SetPicture commands

docs/UserGuide.md
1. Fix grammatical errors
2. Update Command Summary
3. Add 'you' language
fix #140
=> Update UG based on peer review

src/main/java/seedu/address/ui/PersonListPanel.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/LightTheme.css, src/main/resources/view/PersonListPanel.fxml
=> Change font size

src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/model/employee/Email.java
Update Email class and AddCommandParser so that Email is made as an optional field, fixes #145
=> Update Email to be an optional field

src/main/java/seedu/address/logic/commands/SetPictureCommand.java, src/main/java/seedu/address/model/employee/Employee.java, src/main/java/seedu/address/model/employee/PicturePath.java
Fix setpicture to work with jar release
=> Fix setpicture for jar release

docs/UserGuide.md, docs/team/gyulong1.md, docs/team/junhao247.md, docs/team/panavdua.md
Update PPP based on weekly objectives, fixes #228
=> Update my own PPP to current implementations.

src/main/java/seedu/address/Main.java
=> Update main class to create `data` folder from the start.

src/main/java/seedu/address/model/ExecutiveProDb.java, src/main/java/seedu/address/model/employee/Employee.java
Change notion of equality for Employee
=> Branch fix bugs

src/main/java/seedu/address/model/employee/LeaveCounter.java, src/main/java/seedu/address/model/employee/Payroll.java
=> Fix error message for invalid payroll

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/employee/EmployeeId.java, src/main/java/seedu/address/model/employee/LeaveCounter.java, src/test/data/JsonExecutiveProDbStorageTest/invalidAndValidEmployeeExecutiveProDb.json, src/test/data/JsonExecutiveProDbStorageTest/invalidEmployeeExecutiveProDb.json, src/test/data/JsonSerializableExecutiveProDbTest/duplicateEmployeeExecutiveProDb.json, src/test/data/JsonSerializableExecutiveProDbTest/invalidEmployeeExecutiveProDb.json, src/test/data/JsonSerializableExecutiveProDbTest/typicalEmployeesExecutiveProDb.json, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/EditEmployeeDescriptorTest.java, src/test/java/seedu/address/logic/commands/LeaveCommandTest.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/logic/parser/LeaveCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/ExecutiveProDbTest.java, src/test/java/seedu/address/model/employee/AddressTest.java, src/test/java/seedu/address/model/employee/EmailTest.java, src/test/java/seedu/address/model/employee/EmployeeTest.java, src/test/java/seedu/address/model/employee/PicturePathTest.java, src/test/java/seedu/address/model/employee/UniqueEmployeeListTest.java, src/test/java/seedu/address/storage/JsonAdaptedEmployeeTest.java, src/test/java/seedu/address/testutil/EditEmployeeDescriptorBuilder.java, src/test/java/seedu/address/testutil/EmployeeBuilder.java, src/test/java/seedu/address/testutil/EmployeeUtil.java, src/test/java/seedu/address/testutil/TypicalEmployees.java
=> Fix test cases and add test cases for LeaveCommand

src/main/java/seedu/address/logic/commands/BatchAddCommand.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/ModelManager.java, src/test/data/BatchAddTest/duplicates.csv, src/test/data/BatchAddTest/missingFields.csv, src/test/data/BatchAddTest/validEmployees.csv, src/test/java/seedu/address/logic/commands/BatchAddCommandTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/testutil/TypicalEmployees.java
=> Update batchaddcommand test

src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java, src/test/java/seedu/address/logic/parser/FindCommandParserTest.java, src/test/java/seedu/address/testutil/TypicalEmployees.java
=> Add tests for FindCommand

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/LeaveCommand.java, src/main/java/seedu/address/logic/commands/SetPictureCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/model/employee/Employee.java, src/main/java/seedu/address/model/employee/PicturePath.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedEmployee.java, src/main/java/seedu/address/ui/PersonListPanel.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/testutil/EmployeeBuilder.java
Update setpicture command to work similarly to edit command by making a new Employee. Hence Employees are now properly immutable.
=> Update setpicture command to work similarly to edit command

src/main/java/seedu/address/model/employee/FilterByLeaveCountPredicate.java, src/main/java/seedu/address/model/employee/FilterByPayrollPredicate.java, src/test/java/seedu/address/logic/commands/FilterCommandTest.java, src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java, src/test/java/seedu/address/testutil/TypicalEmployees.java
=> Add tests for FilterCommand

docs/DeveloperGuide.md, docs/team/abenx162.md, src/main/java/seedu/address/logic/commands/SetPictureCommand.java
=> Update Ben Xuan's PPP as of 9 April 2023

README.md, docs/DeveloperGuide.md, docs/UserGuide.md, docs/index.md, docs/team/abenx162.md, docs/team/gyulong1.md, docs/team/junhao247.md, docs/team/panavdua.md, docs/team/yanlings.md
Update UserGuide, DeveloperGuide to include invalid file type error message in Planned Enhancements section.
Update PPP headings for every team member.
Update ReadMe's Ui image.
Update index.md's description.
fixes #206 , updates #221
=> Update UserGuide, DeveloperGuide, PPP, Readme and index.md

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/FilterCommand.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/FilterCommandParser.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/model/employee/FilterByLeaveCountPredicate.java, src/main/java/seedu/address/model/employee/FilterByPayrollPredicate.java, src/main/java/seedu/address/model/employee/NameContainsAllKeywordsPredicate.java, src/main/java/seedu/address/model/employee/NameContainsKeywordsPredicate.java
=> Add javadocs

src/test/java/seedu/address/logic/commands/BatchAddCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
=> Implement test case to increase code cov

docs/UserGuide.md
=> UG style fix

docs/team/junhao247.md
=> Update JunHao's PPP
